const fs = require('node:fs');
const path = require('node:path');

const projectRoot = path.resolve(__dirname, '..');
const cssEntryFile = './global.css';
const generatedDirectory = path.join(projectRoot, 'src', 'generated');
const uniwindDirectory = path.dirname(require.resolve('uniwind/package.json'));
const transformerPath = path.join(
  uniwindDirectory,
  'dist',
  'metro',
  'transformer.cjs',
);

function installTransformCapture() {
  const workerPath = require.resolve('metro-transform-worker');

  require.cache[workerPath] = {
    id: workerPath,
    filename: workerPath,
    loaded: true,
    exports: {
      transform: async (_config, _root, _filename, source) => ({
        output: [{data: {code: source.toString('utf8'), css: {}}}],
      }),
    },
  };
}

function writeIfChanged(filename, contents) {
  if (fs.existsSync(filename) && fs.readFileSync(filename, 'utf8') === contents) {
    return;
  }

  fs.writeFileSync(filename, contents);
}

async function compile(transform, platform) {
  const source = fs.readFileSync(path.join(projectRoot, cssEntryFile));
  const result = await transform(
    {
      uniwind: {
        cssEntryFile,
        dtsFile: './src/uniwind-types.d.ts',
        isExpoProject: false,
      },
    },
    projectRoot,
    'global.css',
    source,
    {dev: false, platform, type: 'module'},
  );

  return result.output[0].data.code;
}

async function generate() {
  installTransformCapture();
  const {transform} = require(transformerPath);

  fs.mkdirSync(generatedDirectory, {recursive: true});

  for (const platform of ['ios', 'android', 'native']) {
    const code = await compile(transform, platform);
    writeIfChanged(
      path.join(generatedDirectory, `uniwind.${platform}.js`),
      `/* Generated by scripts/generate-uniwind.cjs. */\n${code}\n`,
    );
  }

  const webCSS = await compile(transform, 'web');
  writeIfChanged(
    path.join(generatedDirectory, 'uniwind.web.css'),
    `/* Generated by scripts/generate-uniwind.cjs. */\n${webCSS}\n`,
  );
}

if (require.main === module) {
  generate().catch(error => {
    console.error(error);
    process.exitCode = 1;
  });
}

module.exports = {generate};
